trigger:
- main

pool:
  name: 'azureagent'
  demands:
  - agent.name -equals azureagent

steps:

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Azure subscription 1(2d1ab503-4ce3-4a5a-9c98-8e755ac8946a)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t hemkumarazure.azurecr.io/web-game:tag 2048-game
      az acr login -n hemkumarazure
      docker push hemkumarazure.azurecr.io/web-game:tag

- script: cat 01_kubernetes_aks/app-deploy.yaml

- task: Kubernetes@1
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Azure subscription 1(2d1ab503-4ce3-4a5a-9c98-8e755ac8946a)'
    azureResourceGroup: 'azurecicd'
    kubernetesCluster: 'azuredevops'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '01_kubernetes_aks'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Azure subscription 1(2d1ab503-4ce3-4a5a-9c98-8e755ac8946a)'